framework:
    default_locale: '%default_locale%'
    translator:
        enabled_locales: '%enabled_locales%'
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%default_locale%'
